server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        #mybatis的配置文件所在路径
  type-aliases-package: com.bjsxt.springcloud.entities     #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       #mapper映射文件所在路径
spring:
  application:
    name: microservicecloud_provider_config_dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5                                            #数据库连接池的最小维持连接数
      initial-size: 5                                       #初始化连接数
      max-total: 5                                           #最大连接数
      max-wait-millis: 200                                  #等待连接的最大超时时间
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicespringcloud_dept8001
    prefer-ip-address: true
info:
  app.name: springCloudLianxi
  company.name: www.atguigu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
